//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoLocadoraMVC3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public CLIENTE()
        {
            this.LOCACAO = new HashSet<LOCACAO>();
        }
    
        public long CD_CLIENTE { get; set; }
        public string NM_CLIENTE { get; set; }
        public string CD_SEXO { get; set; }
        public System.DateTime DT_NASCIMENTO { get; set; }
        public string DS_ENDERECO { get; set; }
        public Nullable<int> NR_ENDERECO { get; set; }
        public string NM_BAIRRO { get; set; }
        public string DS_COMPLEMENTO { get; set; }
        public string NM_CIDADE { get; set; }
        public long VL_SALDO { get; set; }
    
        public virtual ICollection<LOCACAO> LOCACAO { get; set; }
    }
}
