//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoLocadoraMVC3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COPIA
    {
        public COPIA()
        {
            this.LOCACAO = new HashSet<LOCACAO>();
        }
    
        public long CD_COPIA { get; set; }
        public long CD_TITULO { get; set; }
        public string TP_COPIA { get; set; }
    
        public virtual ICollection<LOCACAO> LOCACAO { get; set; }
        public virtual TITULO TITULO { get; set; }
    }
}
