//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoLocadoraMVC3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LOCADORAEntities : DbContext
    {
        public LOCADORAEntities()
            : base("name=LOCADORAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ATOR> ATOR { get; set; }
        public DbSet<CLIENTE> CLIENTE { get; set; }
        public DbSet<COPIA> COPIA { get; set; }
        public DbSet<GENERO> GENERO { get; set; }
        public DbSet<LOCACAO> LOCACAO { get; set; }
        public DbSet<TIPO_TITULO> TIPO_TITULO { get; set; }
        public DbSet<TITULO> TITULO { get; set; }
    }
}
