//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoLocadoraMVC3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TITULO
    {
        public TITULO()
        {
            this.COPIA = new HashSet<COPIA>();
            this.ATOR = new HashSet<ATOR>();
            this.GENERO = new HashSet<GENERO>();
        }
    
        public long CD_TITULO { get; set; }
        public string NM_TITULO { get; set; }
        public string DS_SINOPSE { get; set; }
        public string DS_ORIGEM_TITULO { get; set; }
        public short VL_ANO { get; set; }
        public long CD_TIPO_TITULO { get; set; }
        public byte[] VL_TRAILER { get; set; }
    
        public virtual ICollection<COPIA> COPIA { get; set; }
        public virtual TIPO_TITULO TIPO_TITULO { get; set; }
        public virtual ICollection<ATOR> ATOR { get; set; }
        public virtual ICollection<GENERO> GENERO { get; set; }
    }
}
